export default [
  {
    id: 1,
    postedOn: "11-28-2023",
    title: "iOS Developer",
    company: "Apple",
    type: "Full time",
    experience: "Mid level",
    location: "Remote",
    skills: ["swiftUI", "UiKit", "core data"],
    job_link: "https://www.apple.com/careers/us/",
  },
  {
    id: 2,
    postedOn: "11-25-2023",
    title: "Frontend Developer",
    company: "Amazon",
    type: "Full time",
    experience: "Mid level",
    location: "In-Office",
    skills: ["javascript", "react", "Tailwind css"],
    job_link: "https://www.amazon.jobs/en/",
  },
  {
    id: 3,
    postedOn: "11-29-2023",
    title: "Android Developer",
    company: "Facebook",
    type: "Part time",
    experience: "Senior level",
    location: "Remote",
    skills: ["kotlin", "MVVM"],
    job_link: "https://www.facebook.com/",
  },
  {
    id: 4,
    postedOn: "11-26-2023",
    title: "Developer Advocate",
    company: "Netflix",
    type: "Contract",
    experience: "Junior level",
    location: "Hybrid",
    skills: ["web3", "content creation", "community"],
    job_link: "https://jobs.netflix.com/",
  },
];
